namespace WCell.Constants.Achievements
{
    public enum AchievementCriteriaRequirementType
    {
        None,
        Creature,
        PlayerClassRace,
        PlayerLessHealth,
        PlayerDead,
        Aura1,
        Area,
        Aura2,
        Value,
        Level,
        Gender,
        Disabled,
        MapDifficulty,
        MapPlayerCount,
        Team,
        Drunk,
        Holiday,
        BgLossTeamScore,
        InstanceScript,
        EquippedItemLevel,
        NthBirthday,
        KnownTitle,
        End,
    }
}