
///
/// This file was automatically created, using WCell's CodeFileWriter
/// Date: 7/19/2010
///

namespace WCell.Constants.World
{
    [System.Serializable]
	public enum MapId  : int
	{
        None = -1,
        Silaris = 0,
        RainRiver = 1,
        ConquestLand = 2,
        Alpia = 3,
        NightValey = 4,
        Aquaton = 5,
        SunnyCoast = 6,
        Flamio = 7,
        QueenPalace = 8,
        CastleOfChess = 9,
        FlamioPlains = 10,
        NeptillanNode = 11,
        FlamionMoutain = 12,
        Flabis = 13,
        StagnantDesert = 14,
        DragonLair = 15,
        FirewayForest = 16,
        CastleOfChaos = 17,
        Inferion = 18,
        BatleField = 19,
        DecaronLab= 20,
        FieldOfHonnor = 21,
        OX = 22,
        IceQuarry = 23,
        BurnedoutForest = 24,
        DesolatedMarsh = 25,
        FrigidWastes = 26,
        NeverFall = 27,
        Guildwave = 28,
        Fantagle = 29,
        WindCanyon = 30 ,
		Astrica = 31,
		AlteracValley = 30,
        Elysion = 32,
        Acanpolis = 33,
        Labyrinthos = 34,
        Deadmines = 35,
        NightValeyElite = 36,
		AzsharaCrater = 37,
		CollinsTest = 42,
		WailingCaverns = 43,
		UnusedMonastery = 44,
		RazorfenKraul = 47,
		BlackfathomDeeps = 48,
		Uldaman = 70,
		Gnomeregan = 90,
		SunkenTemple = 109,
		RazorfenDowns = 129,
		EmeraldDream = 169,
		ScarletMonastery = 189,
		ZulFarrak = 209,
		BlackrockSpire = 229,
		BlackrockDepths = 230,
		OnyxiasLair = 249,
		OpeningOfTheDarkPortal = 269,
		Scholomance = 289,
		ZulGurub = 309,
		Stratholme = 329,
		Maraudon = 349,
		DeeprunTram = 369,
		RagefireChasm = 389,
		MoltenCore = 409,
		DireMaul = 429,
		AlliancePVPBarracks = 449,
		HordePVPBarracks = 450,
		DevelopmentLand = 451,
		BlackwingLair = 469,
		WarsongGulch = 489,
		RuinsOfAhnQiraj = 509,
		ArathiBasin = 529,
		Outland = 530,
		AhnQirajTemple = 531,
		Karazhan = 532,
		Naxxramas = 533,
		TheBattleForMountHyjal = 534,
		HellfireCitadelTheShatteredHalls = 540,
		HellfireCitadelTheBloodFurnace = 542,
		HellfireCitadelRamparts = 543,
		MagtheridonsLair = 544,
		CoilfangTheSteamvault = 545,
		CoilfangTheUnderbog = 546,
		CoilfangTheSlavePens = 547,
		CoilfangSerpentshrineCavern = 548,
		TempestKeep = 550,
		TempestKeepTheArcatraz = 552,
		TempestKeepTheBotanica = 553,
		TempestKeepTheMechanar = 554,
		AuchindounShadowLabyrinth = 555,
		AuchindounSethekkHalls = 556,
		AuchindounManaTombs = 557,
		AuchindounAuchenaiCrypts = 558,
		NagrandArena = 559,
		TheEscapeFromDurnholde = 560,
		BladesEdgeArena = 562,
		BlackTemple = 564,
		GruulsLair = 565,
		EyeOfTheStorm = 566,
		ZulAman = 568,
		Northrend = 571,
		RuinsOfLordaeron = 572,
		ExteriorTest = 573,
		UtgardeKeep = 574,
		UtgardePinnacle = 575,
		TheNexus = 576,
		TheOculus = 578,
		TheSunwell = 580,
		TransportRutTheranToAuberdine = 582,
		TransportMenethilToTheramore = 584,
		MagistersTerrace = 585,
		TransportExodarToAuberdine = 586,
		TransportFeathermoonFerry = 587,
		TransportMenethilToAuberdine = 588,
		TransportOrgrimmarToGromGol = 589,
		TransportGromGolToUndercity = 590,
		TransportUndercityToOrgrimmar = 591,
		TransportBoreanTundraTest = 592,
		TransportBootyBayToRatchet = 593,
		TransportHowlingFjordSisterMercyQuest = 594,
		TheCullingOfStratholme = 595,
		TransportNaglfar = 596,
		CraigTest = 597,
		SunwellFixUnused = 598,
		HallsOfStone = 599,
		DrakTharonKeep = 600,
		AzjolNerub = 601,
		HallsOfLightning = 602,
		Ulduar = 603,
		Gundrak = 604,
		DevelopmentLandNonWeightedTextures = 605,
		QAAndDVD = 606,
		StrandOfTheAncients = 607,
		VioletHold = 608,
		EbonHold = 609,
		TransportTirisfalToVengeanceLanding = 610,
		TransportMenethilToValgarde = 612,
		TransportOrgrimmarToWarsongHold = 613,
		TransportStormwindToValianceKeep = 614,
		TheObsidianSanctum = 615,
		TheEyeOfEternity = 616,
		DalaranSewers = 617,
		TheRingOfValor = 618,
		AhnKahetTheOldKingdom = 619,
		TransportMoaKiToUnuPe = 620,
		TransportMoaKiToKamagua = 621,
		TransportOrgrimsHammer = 622,
		TransportTheSkybreaker = 623,
		VaultOfArchavon = 624,
		IsleOfConquest = 628,
		IcecrownCitadel = 631,
		TheForgeOfSouls = 632,
		TransportAllianceAirshipBG = 641,
		TransportHordeAirshipBG = 642,
		TransportOrgrimmarToThunderBluff = 647,
		TrialOfTheCrusader = 649,
		TrialOfTheChampion = 650,
		PitOfSaron = 658,
		HallsOfReflection = 668,
		TransportTheSkybreakerIcecrownCitadelRaid = 672,
		TransportOrgrimsHammerIcecrownCitadelRaid = 673,
		TransportTheSkybreakerICDungeon = 712,
		TransportOrgrimsHammerICDungeon = 713,
		TrasnportTheMightyWindIcecrownCitadelRaid = 718,
		Stormwind = 723,
		TheRubySanctum = 724,

        EasternKingdoms,
        Kalimdor,
		End
	}

}