using WCell.Constants;

namespace WCell.RealmServer.Spells.Auras.Handlers
{
    /// <summary>
    /// Modifies threat generated by attacks of the given DamageSchools
    /// </summary>
    public class ModThreatHandler : AuraEffectHandler
    {
        protected override void Apply()
        {
            for (int index = 0; index < 7; ++index)
                this.Owner.ModThreat((DamageSchool) index, this.SpellEffect.MiscValue);
        }

        protected override void Remove(bool cancelled)
        {
            for (int index = 0; index < 7; ++index)
                this.Owner.ModThreat((DamageSchool) index, -this.SpellEffect.MiscValue);
        }
    }
}