//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class characterrecord
    {
        public long EntityLowId { get; set; }
        public int DisplayId { get; set; }
        public int WatchedFaction { get; set; }
        public int ClassId { get; set; }
        public int Map { get; set; }
        public Nullable<int> CorpseMap { get; set; }
        public Nullable<int> Zone { get; set; }
        public Nullable<int> BindZone { get; set; }
        public int BindMap { get; set; }
        public Nullable<int> GuildId { get; set; }
        public Nullable<int> SummonSpell { get; set; }
        public Nullable<int> PetEntryId { get; set; }
        public int TalentResetPriceTier { get; set; }
        public int KillsTotal { get; set; }
        public int HonorToday { get; set; }
        public int HonorYesterday { get; set; }
        public int LifetimeHonorableKills { get; set; }
        public int HonorPoints { get; set; }
        public int ArenaPoints { get; set; }
        public int AccountId { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastLogout { get; set; }
        public int CharacterFlags { get; set; }
        public int Race { get; set; }
        public int Gender { get; set; }
        public byte Skin { get; set; }
        public byte face { get; set; }
        public byte HairStyle { get; set; }
        public byte HairColor { get; set; }
        public byte FacialHair { get; set; }
        public byte Outfit { get; set; }
        public int Level { get; set; }
        public Nullable<int> Xp { get; set; }
        public int TotalPlayTime { get; set; }
        public int LevelPlayTime { get; set; }
        public byte[] TutorialFlags { get; set; }
        public byte[] ExploredZones { get; set; }
        public float PositionX { get; set; }
        public float PositionY { get; set; }
        public float PositionZ { get; set; }
        public float Orientation { get; set; }
        public Nullable<float> CorpseX { get; set; }
        public Nullable<float> CorpseY { get; set; }
        public Nullable<float> CorpseZ { get; set; }
        public Nullable<float> CorpseO { get; set; }
        public float BindX { get; set; }
        public float BindY { get; set; }
        public float BindZ { get; set; }
        public Nullable<int> RuneSetMask { get; set; }
        public byte[] RuneCooldowns { get; set; }
        public int BaseStrength { get; set; }
        public int BaseStamina { get; set; }
        public int BaseSpirit { get; set; }
        public int BaseIntellect { get; set; }
        public int BaseAgility { get; set; }
        public Nullable<bool> GodMode { get; set; }
        public Nullable<byte> ProfessionLevel { get; set; }
        public int Health { get; set; }
        public int BaseHealth { get; set; }
        public int Power { get; set; }
        public int BasePower { get; set; }
        public long Money { get; set; }
        public byte PetBoxEnchants { get; set; }
        public byte MountBoxExpands { get; set; }
        public byte[] FinishedQuests { get; set; }
        public byte[] FinishedDailyQuests { get; set; }
        public Nullable<int> RestXp { get; set; }
        public Nullable<int> RestTriggerId { get; set; }
        public Nullable<int> NextTaxiVertexId { get; set; }
        public byte[] TaxiMask { get; set; }
        public Nullable<bool> IsPetActive { get; set; }
        public Nullable<int> StableSlotCount { get; set; }
        public Nullable<int> PetSummonedCount { get; set; }
        public Nullable<int> PetCount { get; set; }
        public Nullable<int> PetHealth { get; set; }
        public Nullable<int> PetPower { get; set; }
        public Nullable<int> PrivatePerLevelItemBonusTemplateId { get; set; }
        public Nullable<int> PetDuration { get; set; }
        public Nullable<System.DateTime> LastTalentResetTime { get; set; }
        public Nullable<int> DungeonDifficulty { get; set; }
        public Nullable<int> RaidDifficulty { get; set; }
        public Nullable<int> BattlegroundTeam { get; set; }
        public byte CharNum { get; set; }
        public byte Zodiac { get; set; }
        public Nullable<byte> Asda2Class { get; set; }
        public Nullable<byte> EyesColor { get; set; }
        public Nullable<int> BaseLuck { get; set; }
        public Nullable<int> FreeStatPoints { get; set; }
        public Nullable<int> GlobalChatColorDb { get; set; }
        public byte[] DiscoveredTitles { get; set; }
        public byte[] GetedTitles { get; set; }
        public byte[] LearnedRecipes { get; set; }
        public Nullable<int> FishingLevel { get; set; }
        public Nullable<int> AvatarMask { get; set; }
        public byte[] SettingsFlags { get; set; }
        public Nullable<short> Asda2FactionId { get; set; }
        public Nullable<int> GuildPoints { get; set; }
        public Nullable<short> PreTitleId { get; set; }
        public Nullable<short> PostTitleId { get; set; }
        public Nullable<byte> MaxRepipesCount { get; set; }
        public Nullable<byte> CraftingLevel { get; set; }
        public Nullable<float> CraftingExp { get; set; }
        public Nullable<int> BanPoints { get; set; }
        public Nullable<byte> PremiumWarehouseBagsCount { get; set; }
        public Nullable<byte> PremiumAvatarWarehouseBagsCount { get; set; }
        public string WarehousePassword { get; set; }
        public Nullable<int> Asda2HonorPoints { get; set; }
        public Nullable<int> RebornCount { get; set; }
    }
}
