//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class donations
    {
        public int Id { get; set; }
        public int Wallet { get; set; }
        public int Amount { get; set; }
        public string CharacterName { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public bool IsDelivered { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<System.DateTime> DeliveredDateTime { get; set; }
        public string PayerName { get; set; }
    }
}
